version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: helpdesk
      POSTGRES_USER: helpdesk_user
      POSTGRES_PASSWORD: helpdesk_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - helpdesk_overlay
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  backend:
    image: karencc/helpdesk-cloud-backend:v1
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: postgresql://helpdesk_user:helpdesk_password@postgres:5432/helpdesk
      JWT_SECRET: helpdesk_cloud_secret_2026
      JWT_EXPIRES_IN: 8h
      CORS_ORIGIN: http://localhost
    networks:
      - helpdesk_overlay
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

  frontend:
    image: karencc/helpdesk-cloud-frontend:v1
    networks:
      - helpdesk_overlay
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
      - "443:443"
    configs:
      - source: nginx_default
        target: /etc/nginx/conf.d/default.conf
    networks:
      - helpdesk_overlay
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  prometheus:
    image: prom/prometheus:v2.55.0
    ports:
      - "9090:9090"
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    volumes:
      - prometheus_data:/prometheus
    networks:
      - helpdesk_overlay
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana:11.3.0
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - helpdesk_overlay
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

configs:
  nginx_default:
    file: ./nginx/default.conf

  prometheus_config:
    file: ./monitoring/prometheus/prometheus.yml

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:

networks:
  helpdesk_overlay:
    driver: overlay