global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'helpdesk-backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:4000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
